# Generated by Django 3.2.25 on 2024-07-12 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('hp', models.IntegerField(default=100)),
                ('mp', models.IntegerField(default=10)),
                ('cp', models.IntegerField(default=10)),
                ('dmg', models.IntegerField(default=10)),
                ('exp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('effects', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(default='Idle', max_length=50)),
                ('temp_stats', models.JSONField(default=dict)),
                ('regenerate', models.BooleanField(default=False)),
                ('regenerate_amount', models.IntegerField(default=0)),
                ('lose_health', models.BooleanField(default=False)),
                ('lose_health_amount', models.IntegerField(default=0)),
                ('in_battle', models.BooleanField(default=False)),
                ('completed_locations', models.IntegerField(default=0)),
                ('completed_forest_levels', models.IntegerField(default=0)),
                ('completed_catacombs_levels', models.IntegerField(default=0)),
                ('completed_magma_levels', models.IntegerField(default=0)),
                ('current_forest_level', models.IntegerField(default=0)),
                ('current_catacombs_level', models.IntegerField(default=0)),
                ('current_magma_level', models.IntegerField(default=0)),
                ('dodge_modifier', models.IntegerField(default=0)),
                ('crit_chance_modifier', models.FloatField(default=0.0)),
                ('skills', models.JSONField(blank=True, default=dict)),
                ('skill_effects', models.TextField(default='{}')),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
            },
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('base_hp', models.IntegerField(default=100)),
                ('base_cp', models.IntegerField(default=10)),
                ('base_dmg', models.IntegerField(default=10)),
                ('level', models.IntegerField(default=1)),
                ('enemy_type', models.CharField(default='Generic', max_length=50)),
                ('exp_reward', models.IntegerField(default=50)),
                ('weakened', models.BooleanField(default=False)),
                ('skills', models.JSONField(blank=True, default=dict)),
                ('effects', models.CharField(blank=True, max_length=255, null=True)),
                ('skill_effects', models.TextField(default='{}')),
            ],
        ),
        migrations.CreateModel(
            name='EnemyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('base_hp', models.IntegerField(default=100)),
                ('base_cp', models.IntegerField(default=10)),
                ('base_dmg', models.IntegerField(default=10)),
                ('level', models.IntegerField(default=1)),
                ('enemy_type', models.CharField(default='Generic', max_length=50)),
                ('exp_reward', models.IntegerField(default=50)),
                ('weakened', models.BooleanField(default=False)),
                ('skills', models.JSONField(blank=True, default=dict)),
                ('effects', models.CharField(blank=True, max_length=255, null=True)),
                ('skill_effects', models.TextField(default='{}')),
            ],
        ),
        migrations.CreateModel(
            name='BossBear',
            fields=[
                ('enemymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.enemymodel')),
            ],
            bases=('bot.enemymodel',),
        ),
        migrations.CreateModel(
            name='BossFairy',
            fields=[
                ('enemymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.enemymodel')),
            ],
            bases=('bot.enemymodel',),
        ),
        migrations.CreateModel(
            name='BossPhoenix',
            fields=[
                ('enemymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.enemymodel')),
            ],
            bases=('bot.enemymodel',),
        ),
        migrations.CreateModel(
            name='Cerberus',
            fields=[
                ('enemymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.enemymodel')),
            ],
            bases=('bot.enemymodel',),
        ),
        migrations.CreateModel(
            name='Cobalt',
            fields=[
                ('enemymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.enemymodel')),
            ],
            bases=('bot.enemymodel',),
        ),
        migrations.CreateModel(
            name='Dragon',
            fields=[
                ('enemymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.enemymodel')),
            ],
            bases=('bot.enemymodel',),
        ),
        migrations.CreateModel(
            name='Goblin',
            fields=[
                ('enemymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.enemymodel')),
            ],
            bases=('bot.enemymodel',),
        ),
        migrations.CreateModel(
            name='Golem',
            fields=[
                ('enemymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.enemymodel')),
            ],
            bases=('bot.enemymodel',),
        ),
        migrations.CreateModel(
            name='Hydra',
            fields=[
                ('enemymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.enemymodel')),
            ],
            bases=('bot.enemymodel',),
        ),
        migrations.CreateModel(
            name='Orc',
            fields=[
                ('enemymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.enemymodel')),
            ],
            bases=('bot.enemymodel',),
        ),
        migrations.CreateModel(
            name='Shadow',
            fields=[
                ('enemymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.enemymodel')),
            ],
            bases=('bot.enemymodel',),
        ),
        migrations.CreateModel(
            name='Skeleton',
            fields=[
                ('enemymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.enemymodel')),
            ],
            bases=('bot.enemymodel',),
        ),
        migrations.CreateModel(
            name='Wolf',
            fields=[
                ('enemymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.enemymodel')),
            ],
            bases=('bot.enemymodel',),
        ),
    ]
