# Generated by Django 3.2.25 on 2024-06-27 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(blank=True, max_length=20, null=True)),
                ('hp', models.IntegerField(default=100)),
                ('mp', models.IntegerField(default=50)),
                ('cp', models.IntegerField(default=10)),
                ('dmg', models.IntegerField(default=0)),
                ('exp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('effects', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
            },
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hp', models.IntegerField(default=100)),
                ('cp', models.IntegerField(default=10)),
                ('dmg', models.IntegerField(default=10)),
                ('level', models.IntegerField(default=1)),
                ('enemy_type', models.CharField(default='Generic', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dragon',
            fields=[
                ('enemy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.enemy')),
            ],
            bases=('bot.enemy',),
        ),
        migrations.CreateModel(
            name='Goblin',
            fields=[
                ('enemy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.enemy')),
            ],
            bases=('bot.enemy',),
        ),
        migrations.CreateModel(
            name='Golem',
            fields=[
                ('enemy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.enemy')),
            ],
            bases=('bot.enemy',),
        ),
        migrations.CreateModel(
            name='Orc',
            fields=[
                ('enemy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.enemy')),
            ],
            bases=('bot.enemy',),
        ),
        migrations.CreateModel(
            name='Wolf',
            fields=[
                ('enemy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.enemy')),
            ],
            bases=('bot.enemy',),
        ),
    ]
