# Generated by Django 3.2.25 on 2024-07-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='completed_magma_levels',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='current_catacombs_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='current_forest_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='current_magma_level',
            field=models.IntegerField(default=1),
        ),
    ]
