# Generated by Django 3.2.12 on 2024-06-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='user',
        ),
        migrations.AddField(
            model_name='character',
            name='crit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='dmg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='dodge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='user_id',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='cp',
            field=models.IntegerField(default=10),
        ),
    ]
