# Generated by Django 3.2.25 on 2024-06-28 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enemy',
            old_name='cp',
            new_name='base_cp',
        ),
        migrations.RenameField(
            model_name='enemy',
            old_name='dmg',
            new_name='base_dmg',
        ),
        migrations.RenameField(
            model_name='enemy',
            old_name='hp',
            new_name='base_hp',
        ),
    ]
