# Generated by Django 3.2.25 on 2024-07-12 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20240712_1019'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enemy',
        ),
    ]
