# Generated by Django 3.2.25 on 2024-06-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20240625_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='crit',
            new_name='_crit_chance',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='dodge',
            new_name='_dodge',
        ),
        migrations.AlterField(
            model_name='character',
            name='dmg',
            field=models.IntegerField(default=10),
        ),
    ]
