# Generated by Django 3.2.25 on 2024-07-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_character_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='exp_reward',
            field=models.IntegerField(default=50),
        ),
    ]
