# Generated by Django 3.2.25 on 2024-06-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20240626_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='_crit_chance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='_dodge',
            field=models.FloatField(default=0),
        ),
    ]
