# Generated by Django 3.2.25 on 2024-07-02 14:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_enemy_exp_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='temp_stats',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
