# Generated by Django 3.2.25 on 2024-06-26 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20240626_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='_crit_chance',
            new_name='crit_chance',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='_dodge',
            new_name='dodge',
        ),
        migrations.RemoveField(
            model_name='character',
            name='dmg',
        ),
    ]
