# Generated by Django 3.2.25 on 2024-07-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_character_temp_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='lose_health',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='lose_health_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='regenerate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='regenerate_amount',
            field=models.IntegerField(default=0),
        ),
    ]
