# Generated by Django 3.2.25 on 2024-06-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20240626_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='crit_chance',
            new_name='_crit_chance',
        ),
        migrations.AddField(
            model_name='character',
            name='dmg',
            field=models.IntegerField(default=10),
        ),
    ]
