# Generated by Django 3.2.25 on 2024-06-26 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20240626_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='dodge',
            new_name='_dodge',
        ),
    ]
