# Generated by Django 3.2.25 on 2024-07-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20240703_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='weakened',
            field=models.BooleanField(default=False),
        ),
    ]
