# Generated by Django 3.2.25 on 2024-06-26 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_rename_dodge_character__dodge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='_crit_chance',
            new_name='crit_chance',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='_dodge',
            new_name='dodge',
        ),
    ]
