# Generated by Django 3.2.25 on 2024-06-26 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_auto_20240626_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'verbose_name': 'Character', 'verbose_name_plural': 'Characters'},
        ),
        migrations.RemoveField(
            model_name='character',
            name='crit_chance',
        ),
        migrations.RemoveField(
            model_name='character',
            name='dodge',
        ),
    ]
