# Generated by Django 3.2.25 on 2024-07-03 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_character_in_battle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skeleton',
            fields=[
                ('enemy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.enemy')),
            ],
            bases=('bot.enemy',),
        ),
        migrations.AddField(
            model_name='character',
            name='completed_catacombs_levels',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='completed_forest_levels',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='completed_locations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='completed_magma_levels',
            field=models.IntegerField(default=0),
        ),
    ]
