# Generated by Django 3.2.25 on 2024-07-03 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_auto_20240703_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireElemental',
            fields=[
                ('enemy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.enemy')),
            ],
            bases=('bot.enemy',),
        ),
        migrations.AddField(
            model_name='character',
            name='current_catacombs_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='current_forest_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='current_magma_level',
            field=models.IntegerField(default=1),
        ),
    ]
