# Generated by Django 3.2.25 on 2024-07-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_auto_20240703_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='state',
            field=models.CharField(default='location_selection', max_length=50),
        ),
    ]
