# Generated by Django 3.2.25 on 2024-06-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_alter_character_dmg'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='effects',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
