# Generated by Django 3.2.25 on 2024-07-05 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_auto_20240704_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='BossFairy',
            fields=[
                ('enemy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.enemy')),
            ],
            bases=('bot.enemy',),
        ),
    ]
