# Generated by Django 3.2.25 on 2024-07-05 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_auto_20240705_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enemy',
            old_name='name',
            new_name='nickname',
        ),
    ]
