# Generated by Django 3.2.25 on 2024-07-05 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_rename_name_enemy_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enemy',
            old_name='nickname',
            new_name='name',
        ),
    ]
