# Generated by Django 3.2.25 on 2024-07-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_rename_nickname_enemy_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='effects',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
