# Generated by Django 3.2.25 on 2024-07-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_enemy_effects'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='skill_effects',
            field=models.TextField(default='{}'),
        ),
    ]
