# Generated by Django 3.2.25 on 2024-07-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_character_skill_effects'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='skill_effects',
            field=models.TextField(default='{}'),
        ),
    ]
