# Generated by Django 3.2.25 on 2024-07-07 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0020_enemy_skill_effects'),
    ]

    operations = [
        migrations.CreateModel(
            name='BossPhoenix',
            fields=[
                ('enemy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.enemy')),
            ],
            bases=('bot.enemy',),
        ),
        migrations.CreateModel(
            name='Cerberus',
            fields=[
                ('enemy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.enemy')),
            ],
            bases=('bot.enemy',),
        ),
        migrations.CreateModel(
            name='Cobalt',
            fields=[
                ('enemy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.enemy')),
            ],
            bases=('bot.enemy',),
        ),
        migrations.CreateModel(
            name='Hydra',
            fields=[
                ('enemy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.enemy')),
            ],
            bases=('bot.enemy',),
        ),
        migrations.CreateModel(
            name='Shadow',
            fields=[
                ('enemy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.enemy')),
            ],
            bases=('bot.enemy',),
        ),
        migrations.RenameModel(
            old_name='FireElemental',
            new_name='BossBear',
        ),
    ]
